matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.url:
  - pyspelling.filters.markdown:
    comments: false
    ignores:
    - code
    - pre
    - ul
    - li
    - init
    - npx
  sources:
  - '**/*.md'
  default_encoding: utf-8

