name: Spellcheck Action
on:
  push:
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
    - name: Spell Check
    - uses: dorny/paths-filter@v2.6.0
      id: filter
      with:
        list-files: shell

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
        filters: |
          markdown:
            - added|modified: '*.md'
    - name: Spell Chech Bot 

