name: Spellcheck Action
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
    - uses:  dorny/paths-filter@v2.6.0
        id: filter
        name: Spellcheck
        with:
          list-files: shell
          filters: |
            md:
              - added/modified: '**.md'
      

